SK-197 Implemented search for conversations by name
SAMA-Communications/sama-server pull request #107
Opened 2024-06-24 10:35 UTC by Oleksandr1414

2024-06-24 10:49 UTC, ccvlad approved these changes
LGFM

2024-06-25 06:46 UTC, IgorKhomenko commented on app/providers/operations/conversation/search/index.js
> +    const limit =
could be improved like this, w/o if/else 

```
const limit = Math.min(searchParams.limit || MAIN_CONSTANTS.LIMIT_MAX, MAIN_CONSTANTS.LIMIT_MAX);

```

2024-06-25 06:47 UTC, IgorKhomenko commented
@Oleksandr1414 please do not forget to add tests

2024-06-25 06:47 UTC, IgorKhomenko requested changes
please do not forget to add tests

2024-06-25 13:17 UTC, IgorKhomenko commented
@Oleksandr1414 please also cover documentation for new API

2024-06-26 10:27 UTC, IgorKhomenko approved these changes

2024-06-26 12:55 UTC, merged