SAMA-51 Implemented an event on adding participants to a group chat
SAMA-Communications/sama-server pull request #78
Opened 2023-11-17 14:21 UTC by Oleksandr1414

2023-11-17 15:05 UTC, ccvlad approved these changes

2023-11-20 08:35 UTC, IgorKhomenko commented on app/utils/get_user_name.js
> +export default function getUserName(u) {
rename to `getDiasplayName`

2023-11-20 08:39 UTC, IgorKhomenko commented on app/controllers/conversations.js
> +        );
do we need to add `.filter(p => !!p)` to filter `undefined` values when user is already in chat?

2023-11-20 08:40 UTC, IgorKhomenko commented on app/controllers/conversations.js
> +        const participants = await Promise.all(
`const participants ` -> `const participantsIds `

2023-11-20 08:42 UTC, IgorKhomenko commented on app/controllers/conversations.js
> +              !(await ConversationParticipant.findOne({
instead of looping, can we get all participants using a single query?

2023-11-20 08:44 UTC, IgorKhomenko commented on app/controllers/conversations.js
> +            id: currentUserId + Date.now(),
it should be `ObjectId ` format

2023-11-20 08:48 UTC, IgorKhomenko commented on app/controllers/conversations.js
> +          await PacketProcessor.deliverToUserOrUsers(
I think there is a mistake.
We deliver this message to newly added users. But what about existing participants?

2023-11-20 08:49 UTC, IgorKhomenko requested changes
left some comments to address

2023-11-20 13:57 UTC, IgorKhomenko approved these changes

2023-11-28 10:47 UTC, merged